apiVersion: v1
kind: Service

metadata:
  name: dumbfib
  labels:
    run: dumbfib

spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: dumbfib
  type: LoadBalancer
